package constant

const STATUS_SUCCESS_MSG = "SUCCESS"
const STATUS_SUCCESS_CODE = "0000"

const STATUS_FAIL_MSG = "FAIL"
const STATUS_FAIL_CODE = "9999"

const STATUS_INTERNAL_DB_ERROR_MSG = "INTERNAL DB ERROR"
const STATUS_INTERNAL_DB_ERROR_CODE = "0500"

const STATUS_BAD_REQUEST_MSG = "BAD REQUEST"
const STATUS_BAD_REQUEST_CODE = "0400"

const STATUS_NOT_FOUND_MSG = "NOT FOUND"
const STATUS_NOT_FOUND_CODE = "0404"
