package constant

const USE_YN_Y = "Y"
const USE_YN_N = "N"

const STATUS_SUCCESS_MSG = "SUCCESS"
const STATUS_SUCCESS_CODE = "0000"

const STATUS_FAIL_MSG = "FAIL"
const STATUS_FAIL_CODE = "9999"

const STATUS_INTERNAL_DB_ERROR_MSG = "INTERNAL DB ERROR"
const STATUS_INTERNAL_DB_ERROR_CODE = "0500"

const STATUS_BAD_REQUEST_MSG = "BAD REQUEST"
const STATUS_BAD_REQUEST_CODE = "0400"

const STATUS_NOT_FOUND_MSG = "NOT FOUND"
const STATUS_NOT_FOUND_CODE = "0404"

const STATUS_USER_EXIST_MSG = "USER EXIST"
const STATUS_USER_EXIST_CODE = "0600"

const STATUS_USER_NOT_EXIST_MSG = "USER_NOT_EXIST"
const STATUS_USER_NOT_EXIST_CODE = "0601"

const STATUS_REQUIRE_ID_PASSWORD_MSG = "REQUIRE_ID_PASSWORD"
const STATUS_REQUIRE_ID_PASSWORD_CODE = "0602"

const STATUS_BOARD_NOT_EXIST_MSG = "BOARD_NOT_EXIST"
const STATUS_BOARD_NOT_EXIST_CODE = "0700"
